### PR TITLE
Update Board Queries to support both query JSON and Queries and Annotations

### PR DESCRIPTION
**Pull request by jharley**
This picks up on @tyler-boyd's work in #70, but has a board support both "inline" JSON queries as well as referencing Query objects and Annotations.

### CODE REVIEW

**Review by gsinghsfdc — APPROVED** [review]

**Comment by gsinghsfdc** [comment]
@kvrhdn would it be possible to merge this PR? we're also in the need of this feature

**Comment by jharley** [comment]
@gsinghsfdc Koenraad has just transferred the provider to Honeycomb and I'll be acting as the new maintainer. I need a few days to tidy a few things up, but getting this PR tested and merged and a release cut is my first milestone.

**Comment by gsinghsfdc** [comment]
thanks @jharley!

**Comment by jharley** [comment]
Closed in favour of #100

**Pull request closed without merging**
